### ISSUE TITLE
Feature request: Custom colour

### ISSUE THREAD

**Issue by twolfer** [ivancristina/accent#2]
As below:
Maybe the colour text names could be using the colour itself as a mini preview. 

![BBC4192C-B6F4-421F-878E-6DBABBCA0E51](https://user-images.githubusercontent.com/8477298/71642172-44910b80-2c9f-11ea-9fa4-09001921154b.jpeg)

**Comment by ivancristina** [comment]
Hi, I'm aware of people asking for this, and although I don't label this as `wontfix`, as for now it's not in plan due to lack of time. Will probably add it some other day. Flagging as `enhancement` and closing for now :)
